version: '3.4'

services:
  matchcalculator:
    image: ${DOCKER_REGISTRY-}matchcalculator
    build:
      context: .
      dockerfile: MatchCalculator/Dockerfile
    environment:
      DATABASE_HOST: database
    depends_on:
      - database
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    environment:
      DATABASE_HOST: database
      MATCHCALCULATOR_HOST: matchcalculator
    depends_on:
      - database
      - matchcalculator
  database:
    image: mongo
    restart: always
    command: --quiet --syslog
    expose: 
      - "27017"
    volumes:
      - database-data:/data/db
      - mongo-config:/data/configdb

volumes:
  database-data:
  mongo-config:
